# Generated by Django 4.0.3 on 2022-03-10 23:17

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('slug', models.SlugField(max_length=500)),
                ('description', models.TextField(blank=True, max_length=10000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('thumbnail_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('background_image_link', models.CharField(blank=True, max_length=1000, null=True)),
                ('movie_length', models.CharField(blank=True, max_length=50, null=True)),
                ('release_date', models.DateField(default='2022-01-01')),
                ('movie_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('imdb_rating', models.CharField(blank=True, max_length=100, null=True)),
                ('director', models.CharField(blank=True, max_length=200, null=True)),
                ('actor', models.CharField(blank=True, max_length=1000, null=True)),
                ('language', models.CharField(blank=True, max_length=100, null=True)),
                ('movie_subtitle', models.CharField(blank=True, max_length=100, null=True)),
                ('genre', models.CharField(blank=True, max_length=200, null=True)),
                ('tmdbid', models.IntegerField(blank=True, null=True)),
                ('Date_Added', models.DateField(default=datetime.date.today)),
            ],
        ),
        migrations.CreateModel(
            name='accounts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=30, null=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.IntegerField(blank=True, null=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
