# Generated by Django 4.0.3 on 2022-04-03 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0006_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='image_id',
            field=models.IntegerField(default=-1),
        ),
    ]
